// Auto-generated item flavor text for the Almanac compendium. Keyed by plant/
// fish/forage id; the UI looks up LORE[id] and shows it where space allows.
export const LORE: Record<string, string> = {
  "carrot": "Crisp and earthy, with a natural sweetness that makes a simple snack feel like a feast.",
  "spinach": "Dark leafy greens packed with vitality, reminiscent of early spring mornings.",
  "lettuce": "Tender and refreshing, each leaf holds the promise of a wholesome garden meal.",
  "turnip": "Humble and hearty, with an honest flavor that rewards patient cultivation.",
  "potato": "Starchy comfort in its simplest form, endlessly rewarding to grow and harvest.",
  "radish": "Crisp and peppery, this pint-sized root adds a delightful snap to any harvest.",
  "tomato": "Sun-kissed and fragrant, bursting with the warmth you poured into tending it.",
  "cauliflower": "Pristine white florets unfold like a tiny, edible flower of pure delight.",
  "eggplant": "Sleek and mysterious, this deep purple beauty holds untold culinary secrets.",
  "strawberry": "Jewel-like berries perfumed with summer, nature's candy at peak sweetness.",
  "beet": "Earthen and rich, deep crimson roots pulse with the soil's own vitality.",
  "cucumber": "Cool and crisp, its smooth skin glistens with the dew of countless careful mornings.",
  "watermelon": "A summery treasure, heavy with juice and promise of refreshment in the warmest days.",
  "corn": "Golden kernels gleam like captured sunshine, ready to nourish and delight.",
  "pumpkin": "Enormous and golden, a harvest triumph that marks the turning of seasons.",
  "dragonfruit": "Scales of magenta and emerald hide pale, speckled flesh that tastes like dreams.",
  "pinkcabbage": "Layers of rose and cream spiral outward in nature's own hypnotic artwork.",
  "goldencorn": "Kernels of luminous gold whisper of something rare and precious from the earth.",
  "bluerose": "Petals of impossible azure shimmer with an otherworldly, beguiling grace.",
  "frostpumpkin": "Crystalline and ethereal, this winter miracle glows with ancient magical cold.",
  "sunpetal": "Golden petals that hold the warmth of a thousand sunny afternoons.",
  "starfruit": "A shimmering star born from soil, its light never quite fading.",
  "moonpetal": "Pale and luminous, it blooms only when twilight kisses the earth.",
  "nebula": "A swirling cosmic flower that smells of stardust and ancient wonder.",
  "galaxyfruit": "An orb of spiraling starlight—each bite tastes like the universe itself.",
  "voidbloom": "A haunting obsidian flower that seems to drink in light around it.",
  "aqua_water_lily": "Serene white petals floating on mirror-still water, impossibly perfect.",
  "aqua_lotus_root": "A tender root with the sweetness of morning dew and earth.",
  "aqua_kelp_bloom": "Translucent green fronds that shimmer like silk underwater.",
  "aqua_river_reed": "A slender reed with a gentle rustle that sounds like flowing water.",
  "aqua_pearl_lily": "A legendary bloom with petals of mother-of-pearl and liquid magic.",
  "aqua_tidal_bloom": "It throbs gently like a heartbeat, calling to the deep ocean.",
  "aqua_water_chestnut": "A rare fruit with a crisp sweetness from depths untouched by sunlight.",
  "aqua_celestial_kelp": "Kelp woven from starlight itself, it shimmers with divine grace.",
  "cnf_sugarplum": "A plump, purple fruit that smells like Christmas dreams come true.",
  "cnf_caramel_pod": "Sweet caramel dreaming in a pod, warm and impossibly delicious.",
  "cnf_cottoncandy_bloom": "Spun sugar that somehow grew in soil, soft pink and entirely magical.",
  "cnf_gumdrop_berry": "Jewel-like berries that taste of childhood wonder and pure joy.",
  "cnf_lollipop_lily": "A whimsical flower that seems to glow with sugared sweetness.",
  "cnf_marshmallow_puff": "Impossibly fluffy clouds given form, soft and divinely indulgent.",
  "cnf_honeycomb_fruit": "Sticky-sweet and glowing with inner light, each cell holds nectar that seems to shimmer.",
  "cnf_peppermint_bulb": "Crystalline layers of candy-striped root sparkle with an otherworldly minty chill.",
  "emb_magma_bloom": "A flower that refuses to cool, its petals seem carved from living flame and molten stone.",
  "emb_ember_chili": "Scarlet and trembling with heat, this pepper radiates warmth even in shadow.",
  "emb_ashpetal": "Delicate gray petals coated in fine ash drift gently, carrying the scent of distant fires.",
  "emb_obsidian_fruit": "Black as midnight and smooth as glass, this fruit reflects no light yet seems to hold it.",
  "emb_cinder_lotus": "Petals of fading red and gold unfold in impossible angles, defying the laws of nature.",
  "emb_phoenix_pepper": "Crimson and crackling with faint embers, this pepper rekindles itself endlessly.",
  "emb_lavafruit": "Molten orange and glowing within, this fruit pulses like a heart still beating with fire.",
  "emb_sunforge_bloom": "A blossom forged in golden flames, its petals radiate warmth and raw celestial power.",
  "aut_persimmon": "Plump and amber-hued, this orb bursts with summery sweetness wrapped in autumn's robes.",
  "aut_pomegranate": "Jeweled seed chambers glisten ruby-red, each one a tiny promise of tart and spiced joy.",
  "aut_maple_gourd": "Swirled in caramel and copper, this squash tastes like forest walks and cozy afternoons.",
  "aut_harvest_squash": "Golden and hefty, it smells of harvest festivals and hearth fires long remembered.",
  "aut_candy_corn": "Kernels striped like sunset candy, sweet enough to make you forget it's technically maize.",
  "aut_cinnamon_fern": "Fronds dry to a warm bronze, releasing spice with every gentle touch or whispered breeze.",
  "aut_amber_wheat": "Grain turned to liquid gold, each stalk glimmers as though the sun itself was woven in.",
  "aut_autumn_essence": "The very soul of fall crystallized, rare and perfect, it carries every warm memory at once.",
  "vine_table_grapes": "Plump and purple-green, these grapes taste of summer picnics and lazy afternoons by the vineyard.",
  "vine_concord_cascade": "Deep purple clusters cascade with a musky sweetness that tastes like bottled twilight joy.",
  "vine_kiwi_emerald": "Jewel-bright berries with a sweet-tart soul. Simply exquisite.",
  "vine_hoppy_gold": "Golden wine grapes that sparkle with honeyed warmth and bouncy energy.",
  "vine_scuppernong_bronze": "Plump bronze pearls of pure summer bliss, rich and mellow.",
  "vine_muscadine_ruby": "Deep crimson jewels that taste of sunset and ancient vineyards.",
  "vine_dragon_crimson": "Fearsome berries that glow like dragon's fire, delightfully complex.",
  "vine_starfruit_vine": "Cosmic fruits that shimmer with silver starlight and impossible flavor.",
  "cac_prickly_pear": "Humble cactus fruit with hidden sweetness and prickly charm.",
  "cac_dragon_flame": "Burning-hot flowers that blaze crimson, spicy and alive.",
  "cac_moonlit_aloe": "Silvery succulent that glows softly, soothing and mystical.",
  "cac_golden_agave": "Heart of amber radiance, distilled centuries of desert sun.",
  "cac_barrel_bloom": "Tiny flower crowns atop ancient barrel forms, resilient and dear.",
  "cac_saguaro_jewel": "Majestic crown jewel of cacti, blooming once in a lifetime.",
  "cac_jade_heart": "Luminous green stone-like bloom, embodying desert eternity itself.",
  "cac_desert_crown": "Impossible flower of pure legend, radiating primal desert magic.",
  "cit_lemon": "Bright and cheerful, this sunny sphere lifts the soul instantly.",
  "cit_lime": "Zesty verdant orbs bursting with tart vigor and citrus grace.",
  "cit_orange": "Glowing golden sphere of pure citrus joy, warm and nourishing.",
  "cit_grapefruit": "Blushing pink-hued orbs, refreshingly bitter and sweetly balanced.",
  "cit_kumquat": "Dainty jewels of concentrated citrus essence, perfectly petite.",
  "cit_yuzu": "Rare moonlit treasure, floral and haunting with unearthly aromatic depth.",
  "cit_bergamot": "A fragrant orb of mystique—its zest sparks with floral notes that linger on your fingertips long after.",
  "cit_blood_orange": "Deep crimson flesh glows like captured sunlight, its sweet tang almost too rich to believe.",
  "nut_almond": "Smooth and pale, this kernel holds a delicate sweetness that warms from within.",
  "nut_walnut": "A sturdy dark shell guards a rich, earthy treasure—humble but honest.",
  "nut_hazelnut": "Russet-brown perfection, offering a buttery depth that feels like autumn's gift.",
  "nut_pistachio": "Pale jade nestled in its shell—a tiny jewel with a gentle, lingering charm.",
  "nut_chestnut": "Glossy and deep, this nut roasts to a tender sweetness that promises cozy evenings.",
  "nut_macadamia": "Silvery and smooth as moonlight—a luxurious kernel with buttery richness.",
  "nut_pine": "Crystalline wonder from the highest peaks—its resin holds the secrets of starlight itself.",
  "nut_cacao": "Dark as midnight, fragrant as dreams—this bean holds the universe in its bitter-sweet warmth.",
  "heir_heirloom_tomato": "A stalwart red orb, simple and true, carrying the flavor of generations past.",
  "heir_purple_carrot": "Striking violet root, sweet and earthy—proof that beauty and nutrition are one.",
  "heir_romanesco": "Spiraling green fractals form a living mandala, crisp and subtly nutty.",
  "heir_kohlrabi": "Pale jade bulb, tender and crisp—an alien gift from your own garden soil.",
  "heir_salsify": "Slender root with a delicate oyster-like sweetness that surprises the palate.",
  "heir_fennel": "Bronze-hued fronds exhale licorice dreams—elegant and mysteriously aromatic.",
  "heir_artichoke": "Layered emerald petals unfold like secrets, each bite revealing hidden sweetness.",
  "heir_rainbow_cauli": "Impossible spectrum of rosy, gold, and emerald hues—ordinary soil births wonders.",
  "myth_mandrake_root": "A twisted, humanoid form whispers of ancient magic—handle with reverence and awe.",
  "myth_moonflower_bloom": "Luminescent petals that seem to glow from within—night's most wondrous treasure.",
  "myth_nightshade_essence": "A shimmering vial of midnight petals that whisper with ancient secrets.",
  "myth_fairycap_cluster": "Delicate toadstools that glow faintly, as if lit by tiny lanterns.",
  "myth_witch_hazel_blossom": "Golden blossoms that bloom only under moonlight, humming softly.",
  "myth_dreamleaf_essence": "Iridescent leaves that shimmer like memories made tangible.",
  "myth_spirit_lotus_petals": "Ethereal petals that drift on an unseen breeze, touched by magic.",
  "cry_gemfruit": "A radiant fruit that catches light like a raw gemstone.",
  "cry_quartz_blossom": "Crystalline petals that refract sunlight into countless rainbows.",
  "cry_amethyst_pod": "A deep purple pod with veins of glimmering crystal running through it.",
  "cry_opal_berry": "A luminous berry that shifts colors with every angle you view it.",
  "cry_diamond_lotus": "A breathtaking flower with petals as clear and faceted as diamonds.",
  "cry_prism_vine": "A shimmering vine whose leaves bend light into a full spectrum.",
  "cry_celestial_crown": "A crown-like flower that sparkles with cosmic starlight.",
  "cos_cometberry": "A berry that trails faint light, as if a comet just brushed past.",
  "cos_nebulaguord": "A mesmerizing gourd swirled with colors like a distant nebula.",
  "cos_starbloom": "A flower whose petals glow with the warmth of distant stars.",
  "cos_meteormelon": "A melon with a dark, speckled rind that feels warm to the touch.",
  "cos_solarlotus": "A lotus that radiates gentle warmth, petals glowing like the sun itself.",
  "cos_voidfig": "A deep indigo fig that seems to absorb light, humming with void energy.",
  "cos_galaxygrape": "Grapes that swirl with nebula hues, each one a tiny galaxy.",
  "trop_mango_gold": "A golden mango so bright it seems to glow from within.",
  "trop_papaya_sunset": "A fruit that glows with the warm hues of dusk, its sweet fragrance conjuring tropical breezes.",
  "trop_guava_emerald": "Bright and tangy, this verdant guava practically hums with vitality and refreshment.",
  "trop_passionfruit_royal": "An exotic treasure wreathed in majesty, its seeds burst with intoxicating flavor.",
  "trop_rambutan_crimson": "A spiky jewel of deep crimson, its translucent flesh promises an adventure of taste.",
  "trop_jackfruit_amber": "A legendary golden giant, its custard-like sweetness feels like tasting pure sunlight.",
  "trop_soursop_moonlight": "Whispers of starlight cling to its creamy flesh, sweet and mysteriously ethereal.",
  "flwr_crimson_tulip": "Velvet petals in deep red seem to hold the heart of a smoldering ember.",
  "flwr_golden_sunflower": "Radiant and cheerful, its face follows the sun with unwavering, boundless joy.",
  "flwr_midnight_orchid": "A flower born of shadow and secrets, blooming in colors only dreams dare explore.",
  "flwr_celestial_lotus": "Its petals shimmer with starlight, as though plucked from the heavens themselves.",
  "flwr_royal_peony": "A blossom of unmatched elegance, layered petals brim with regal grace and grandeur.",
  "flwr_twilight_dahlia": "Where day meets night, this flower blooms in colors that defy ordinary naming.",
  "flwr_sapphire_iris": "A gem among blooms, its silken petals capture the depth of a perfect summer sky.",
  "berry_crimson_raspberry": "Jewel-like and sweet, these berries stain your fingers with their vibrant passion.",
  "berry_shadow_blackberry": "Dark and mysterious, each berry holds a subtle, complex sweetness worth savoring.",
  "berry_golden_gooseberry": "Tart and bright, these golden orbs offer tangy refreshment and natural cheer.",
  "berry_scarlet_cranberry": "A tart treasure, these scarlet gems add a sharp, delightful zing to any harvest.",
  "berry_midnight_elderberry": "Deep purple globes bearing an ancient, almost mystical flavor and richness.",
  "berry_amethyst_currant": "Lustrous jewels of deep purple that gleam with an otherworldly, sweet depth.",
  "berry_twilight_boysenberry": "A magical blend where berry flavors dance between day and night in harmony.",
  "melon_cantaloupe": "A golden orb that captures the warmth of summer mornings in its netted rind.",
  "melon_honeydew": "Pale and mysterious, this melon glows softly like moonlight through cream.",
  "melon_zucchini": "Smooth as silk and deep green, perfect for tucking into evening meals.",
  "melon_butternut": "Rich amber skin holds the sweetness of autumn harvest in every bite.",
  "melon_acorn": "Ribbed and dark as obsidian, these small squashes carry surprising warmth within.",
  "melon_bottle": "A vibrant red gourd with a peculiar neck, perfect for storing seeds or secrets.",
  "melon_winter": "Shimmering with supernatural colors, this melon seems to hold all seasons at once.",
  "pep_jalapeno": "A fiery little pepper with a snap of heat and smoky depth.",
  "pep_golden_bell": "Sunshine captured in pepper form, bright and cheerful on any table.",
  "pep_habanero_fire": "Deceptively beautiful and intensely hot, a true test of your courage.",
  "pep_ghostly_specter": "Pale and haunting, this spectral pepper whispers of mysteries untold.",
  "pep_midnight_eggplant": "Deep purple-black and almost liquid-looking, dreamy and exotic.",
  "pep_cosmic_tomatillo": "Swirled with starlight and wonder, tastes like dreams of distant worlds.",
  "pep_infernal_nightshade": "A cursed beauty pulsing with otherworldly fire and ancient power.",
  "root_parsnip": "A humble white root that brings comfort and simple goodness to the table.",
  "root_golden_yam": "Glowing orange inside, this yam warms the soul and fills the belly.",
  "root_ginger": "Knobby and golden, packed with warming spice that tingles on the tongue.",
  "root_purple_rutabaga": "Earthy and royal, this deep purple root adds hearty flavor to any meal.",
  "root_sweet_potato": "Creamy orange flesh bursting with natural sweetness and autumn nostalgia.",
  "root_daikon_star": "Sliced to reveal a perfect star pattern inside, nature's own hidden treasure.",
  "root_taro_essence": "Hauntingly smooth root with a pearlescent sheen, whispers of otherworldly sweetness.",
  "leaf_kale": "Hearty, crinkled leaves that seem to hold the morning dew all day long.",
  "leaf_chard": "Vibrant stems ripple with unexpected colors—nature's painted canvas.",
  "leaf_bok_choy": "Tender stalks nestle together like they're huddling for warmth.",
  "leaf_arugula": "Peppery leaves with a delicate bite, bright with the taste of spring.",
  "leaf_collard": "Sturdy, silvered leaves that taste of slow, patient earth-warmth.",
  "leaf_watercress": "Delicate fronds that grew in cold, clear water, tender and surprisingly spicy.",
  "leaf_romaine": "Crisp and satisfying, each leaf a perfect little vessel for simple goodness.",
  "herb_basil": "Fragrant golden leaves that seem to hold summer's warm light within.",
  "herb_thyme": "Tiny jeweled leaves that hum with twilight magic and ancient memory.",
  "herb_rosemary": "Needle-fine branches glow faintly under moonlight, kissed by starlight.",
  "herb_sage": "Velvety leaves whisper of ancient wisdom and moonlit ceremonies.",
  "herb_cilantro": "Feathery, verdant fronds with a zesty snap of wonder and strangeness.",
  "herb_saffron": "Precious crimson threads, rare as captured moonbeams and twice as precious.",
  "herb_lavender": "Ethereal purple sprigs drift with dreams, calming and impossibly beautiful.",
  "grain_golden_wheat": "Plump kernels gleam like tiny suns, heavy with promise and warmth.",
  "grain_emerald_barley": "Emerald grains tumble like precious stones, cool and deeply nourishing.",
  "grain_jade_rice": "Smooth jade-tinted grains cluster densely, each one pure and patient.",
  "grain_amber_soybean": "Warm amber pods hold legumes that taste of earth and honey.",
  "grain_sapphire_lentil": "Tiny gems striped with sapphire—small but mighty with goodness.",
  "grain_crimson_chickpea": "These deep red legumes have a nutty sweetness and earn their place in every hearty stew.",
  "grain_starlight_quinoa": "Tiny grains that shimmer like captured starlight, wholesome and gently earthy.",
  "orch_honeycrisp": "A cheerful apple that shatters between your teeth with juice and honey-crisp sweetness.",
  "orch_golden_pear": "Soft gold fruit with a buttery core that melts on your tongue without fail.",
  "orch_damson_plum": "Small and deeply purple, these plums are tart and floral, perfect for preserves.",
  "orch_adriatic_fig": "Amber-fleshed and honey-sweet, these figs taste like you've found a hidden garden.",
  "orch_royal_apricot": "Regal golden-orange stone fruit bursting with an almost impossible sweetness.",
  "orch_mulberry_midnight": "Deep black berries that stain your fingers, tasting of summer and secrets.",
  "orch_quince_celestial": "A luminous fruit that shifts between gold and rose; its fragrance is pure magic.",
  "stf_golden_peach": "A downy golden orb that releases a perfume of summer warmth with every bite.",
  "stf_crimson_nectarine": "Smooth-skinned and deep red, this fruit is like biting into a sunset.",
  "stf_ruby_cherry": "Jewel-bright and bursting with tart-sweet flavor, these are nature's perfect candies.",
  "stf_twilight_plum": "Purple as dusk with a complexity that unfolds like a melody on your palate.",
  "stf_jade_olive": "An ethereal green that seems to glow; its taste is briny, rich, and otherworldly.",
  "stf_sunset_lychee": "Translucent flesh encased in bumpy skin, tasting of floral sweetness and rose water dreams.",
  "stf_celestial_date": "Time itself seems to have sweetened this mystical fruit into caramel perfection.",
  "minnow": "A silver flash, small but honest; beloved by every creature in the stream.",
  "bluegill": "Hardy little sun-lover with a gentle flavor, backbone of many a fisherman's meal.",
  "sardine": "Silvery shoal fish that shine like new coins in your net.",
  "perch": "A spirited fish with fine flesh and delicate flavor, prized by discerning cooks.",
  "goldfish": "A cheerful little swimmer with gleaming scales, bobbing contentedly in your hands.",
  "shrimp": "Tiny, delicate crustaceans with a subtle sweetness you can almost taste.",
  "koi": "Ornamental and graceful, its spots seem to shimmer in the light.",
  "bass": "A feisty fighter with bold stripes and a hearty, meaty flavor.",
  "trout": "Crystal-bright with rainbow hues that dance along its silvery side.",
  "catfish": "Whiskered and sturdy, it has a rich, earthy taste to it.",
  "snapper": "Deep crimson scales that glow like embers of a fading fire.",
  "mahimahi": "Vibrant and spirited, this swift hunter embodies the ocean's vitality.",
  "pufferfish": "Delicately spiky and absolutely mesmerizing—approach with respect and awe.",
  "angelfish": "A floating jewel of deep blue and gold, impossibly serene.",
  "moonfish": "Luminous and ethereal, its glow mirrors the grace of a full moon.",
  "manta": "Majestic and vast, its fins cut through water like silk through air.",
  "betta": "Crimson as blood and fire, with an elegance that seems almost sentient.",
  "coelacanth": "Ancient scales that predate empires, still holding secrets of the deep.",
  "swordfish": "Sleek and deadly, bearing a blade that seems forged by fate itself.",
  "ghostshark": "A phantom of the depths, pale and otherworldly, barely visible.",
  "prismtang": "Every scale refracts light into impossible, ever-shifting colors.",
  "axolotl": "Rainbow-crowned and mystical, it seems to hold dreams within its form.",
  "kraken": "Void-black tentacles writhe with an intelligence that transcends mortality.",
  "eel": "Colossal and serpentine, its essence channels the chaos of creation.",
  "nf_sunfish": "A cheerful little fish that glimmers like sunlight on water, always seems to smile.",
  "nf_mudskipper": "A nimble creek-dweller with a personality bigger than its size, loves to explore.",
  "nf_saltherring": "Silvery and plump, a staple catch with a hearty, satisfying flavor.",
  "nf_speckled_perch": "Delicate patterns speckle its scales like stars scattered across twilight.",
  "nf_ribbon_eel": "Elegant as flowing silk, this creature dances through water with mesmerizing grace.",
  "nf_copperfin": "Burnished copper scales catch the light with an almost metallic glow.",
  "nf_duskray": "A mysterious creature that emerges as dusk falls, draped in deepening shadows.",
  "nf_ironjaw": "Fearsome and ancient, this predator bears a jaw forged by centuries of mystery.",
  "nf_abyssal_barb": "A creature from fathomless depths, trailing an aura of primordial darkness.",
  "nf_veilfish": "Gossamer fins shimmer between worlds, as though half-seen in a dream.",
  "nf_moonwhisker": "Luminescent whiskers guide this rare fish through moonlit waters of legend.",
  "nf_gilded_sturgeon": "Encrusted with shimmering gold, a living relic of beauty and ancient power.",
  "nf_tempest_shark": "Crackling with storm energy, this apex being moves with divine fury.",
  "nf_prism_lantern": "Light refracts through its form into infinite rainbow spectra, utterly mesmerizing.",
  "nf_aurora_koi": "Painted with the dancing lights of the aurora, a sight beyond mortal reckoning.",
  "nf_starweave": "Woven from starlight itself, this ethereal creature hums with celestial harmony.",
  "nf_void_carp": "An abyssal dream made flesh, radiating the profound mystery of the infinite void.",
  "nf_sol_leviathan": "A being of solar majesty, its presence warmer than a thousand suns combined.",
  "nf2_mudskipper": "A silt-dwelling jumper with surprising charm and an adventurous spirit.",
  "nf2_silverling": "Gleaming like moonlight on water, these small precious catches warm the heart.",
  "nf2_sandperch": "A speckled fish with sand-smooth scales that glimmer in shallow waters.",
  "nf2_tideguppy": "Tiny and iridescent, these feisty little fish dart through the surf.",
  "nf2_brookdarter": "Swift and slender, a darling of clear, cool streams.",
  "nf2_coralsnapper": "A fiery orange fish with a strong jaw and appetite to match.",
  "nf2_fenneltrout": "Delicate and fragrant, as if the water itself smells of herbs.",
  "nf2_saltwhisker": "A wise old fish with whiskers that tingle in salt spray.",
  "nf2_glasseel": "Ethereal and translucent, it glows softly in the darkest depths.",
  "nf2_moonbream": "A dreamy silvery creature that seems to hold moonlight in its scales.",
  "nf2_vaultpike": "A legendary hunter of the deep, armored in ancient, gleaming plate.",
  "nf2_deepcrown": "An impossible fish crowned with bioluminescent jewels from the abyss.",
  "nf2_emberfin": "Its fins crackle with inner fire, burning brighter than stars.",
  "nf2_abyssalray": "A phantasmal leviathan that dwells where light itself drowns.",
  "nf2_solarshark": "An immense radiant beast that swallows sunlight and hungers for more.",
  "nf2_dawnloach": "Born at the world's first dawn, swimming through timeless memory.",
  "nf2_spectralsalmon": "A fish of pure refracted light, existing between moments.",
  "nf2_voidleviathan": "An entity so vast and ancient it bends the sea around its will.",
  "nf2_starweaverfish": "It swims through threads of starlight, weaving cosmic songs.",
  "nf2_eternaltide": "The very heart of the ocean, eternal and impossibly serene.",
  "mushroom": "A humble wild mushroom with earthy wisdom and a gentle umami warmth.",
  "berries": "Sweet wild berries bursting with bright, sun-ripened flavor.",
  "snowdrop": "A delicate white bloom that pushes through winter's chill, cold as starlight.",
  "herb": "Dried and bundled with care, these leaves mend what ails you.",
  "blueberries": "Plump berries that glow faintly under moonlight, sweet and mysterious.",
  "crystal": "A shard that catches light and scatters it into tiny rainbows.",
  "geode": "Rough stone hiding a warm amber heart—nature's treasure box.",
  "goldcap": "A prized mushroom capped in shimmering gold, worth its weight.",
  "nfg_pebblecap": "Tiny spotted mushrooms that dot the shaded forest floor.",
  "nfg_cloverbloom": "A four-leafed wonder that brings whispers of luck.",
  "nfg_duskshroom": "Glowing softly at dusk, this mushroom feels borrowed from twilight.",
  "nfg_sunpetal": "Petals warm to the touch, holding bottled sunshine.",
  "nfg_ironflint": "Hard as stone and sharp, struck to make sparks dance.",
  "nfg_ghostbell": "Pale silvery flowers that chime softly in the breeze.",
  "nfg_crimsonwort": "Deep red herb that seems to pulse with quiet strength.",
  "nfg_voidcrystal": "A dark shard that swallows light and whispers of deep magic.",
  "nfg2_speckled_cap": "Mushroom spotted like the night sky, precious and strange.",
  "nfg2_dusk_petal": "Twilight itself captured in a single, silken petal.",
  "nfg2_mossy_cobble": "An ancient stone dressed in velvet moss, old as memory.",
  "nfg2_glimmer_shard": "It catches your eye and holds it, shimmering with wonder.",
  "nfg2_ember_bloom": "Flowers that glow like dying coals, warm and alive.",
  "nfg2_voidheart_gem": "A gem that seems to contain unfathomable depths and cosmic beauty.",
};

export function loreFor(id: string): string | undefined {
  return LORE[id];
}
